<!DOCTYPE html>
<html>
<head>
    <title>Invoice</title>
    <style>
        body { font-family: sans-serif; }
        .container { width: 100%; margin: 0 auto; }
        .header { text-align: center; margin-bottom: 20px; }
        .content { margin-bottom: 20px; }
        .table { width: 100%; border-collapse: collapse; }
        .table th, .table td { border: 1px solid #ddd; padding: 8px; }
        .table th { background-color: #f2f2f2; }
        .text-right { text-align: right; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Invoice</h1>
        </div>
        <div class="content">
            <p><strong>Invoice ID:</strong> {{ $invoiceBill->id }}</p>
            <p><strong>Generated by:</strong> {{ $invoiceBill->user->name }}</p>
            <p><strong>Date:</strong> {{ $invoiceBill->created_at->format('Y-m-d') }}</p>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>Trip Name</th>
                    <th>Guest Name</th>
                    <th>Amount</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ $invoiceBill->trip->trip_name }}</td>
                    <td>{{ $invoiceBill->trip->guest_name }}</td>
                    <td class="text-right">PKR {{ number_format($invoiceBill->amount, 2) }}</td>
                </tr>
            </tbody>
        </table>
        <div class="content" style="margin-top: 20px;">
            <p><strong>Details:</strong></p>
            <p>{{ $invoiceBill->details }}</p>
        </div>
        <div class="content">
            <p><strong>QR Code:</strong></p>
            <img src="data:image/png;base64,{{ base64_encode(\SimpleSoftwareIO\QrCode\Facades\QrCode::format('png')->size(150)->generate($invoiceBill->payload)) }}" alt="QR Code">
        </div>
    </div>
</body>
</html>
