<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Invoice Bill Details') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-xl sm:rounded-lg">
                <div class="p-6 lg:p-8 bg-white dark:bg-gray-800 dark:bg-gradient-to-bl dark:from-gray-700/50 dark:via-transparent border-b border-gray-200 dark:border-gray-700">
                    <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
                        <div>
                            <h3 class="text-lg font-medium text-gray-900 dark:text-gray-100">QR Code</h3>
                            <div class="mt-4" id="qrcode"></div>
                        </div>
                        <div>
                            <h3 class="text-lg font-medium text-gray-900 dark:text-gray-100">Details</h3>
                            <div class="mt-4 space-y-4">
                                <div>
                                    <p class="text-sm font-medium text-gray-500 dark:text-gray-400">Amount</p>
                                    <p class="text-lg font-semibold text-gray-900 dark:text-gray-100">PKR {{ number_format($invoiceBill->amount, 2) }}</p>
                                </div>
                                <div>
                                    <p class="text-sm font-medium text-gray-500 dark:text-gray-400">Transaction Particulars</p>
                                    <p class="text-lg font-semibold text-gray-900 dark:text-gray-100">{{ $invoiceBill->transaction_particulars ?? '-' }}</p>
                                </div>
                                <div>
                                    <p class="text-sm font-medium text-gray-500 dark:text-gray-400">Transaction Date</p>
                                    <p class="text-lg font-semibold text-gray-900 dark:text-gray-100">{{ $invoiceBill->transaction_date ? $invoiceBill->transaction_date->format('Y-m-d H:i') : '-' }}</p>
                                </div>
                                <div>
                                    <p class="text-sm font-medium text-gray-500 dark:text-gray-400">Payload</p>
                                    <p class="text-sm font-mono text-gray-700 dark:text-gray-300 break-all">{{ $invoiceBill->payload }}</p>
                                </div>
                                <div>
                                    <p class="text-sm font-medium text-gray-500 dark:text-gray-400">Generated by</p>
                                    <p class="text-lg font-semibold text-gray-900 dark:text-gray-100">{{ $invoiceBill->user->name }}</p>
                                </div>
                            </div>
                        </div>
                        <div>
                            <h3 class="text-lg font-medium text-gray-900 dark:text-gray-100">Trip Information</h3>
                            <div class="mt-4 space-y-4">
                                <div>
                                    <p class="text-sm font-medium text-gray-500 dark:text-gray-400">Trip Name</p>
                                    <p class="text-lg font-semibold text-gray-900 dark:text-gray-100">{{ $invoiceBill->trip->trip_name }}</p>
                                </div>
                                <div>
                                    <p class="text-sm font-medium text-gray-500 dark:text-gray-400">Guest Name</p>
                                    <p class="text-lg font-semibold text-gray-900 dark:text-gray-100">{{ $invoiceBill->trip->guest_name }}</p>
                                </div>
                                <div>
                                    <p class="text-sm font-medium text-gray-500 dark:text-gray-400">Check-in Date</p>
                                    <p class="text-lg font-semibold text-gray-900 dark:text-gray-100">{{ $invoiceBill->trip->check_in_date ? \Carbon\Carbon::parse($invoiceBill->trip->check_in_date)->format('Y-m-d') : '-' }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="flex items-center justify-end mt-6">
                        <a href="{{ route('invoice-bills.download', $invoiceBill) }}" class="inline-flex items-center px-4 py-2 bg-blue-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-blue-700 focus:bg-blue-700 active:bg-blue-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 transition ease-in-out duration-150">
                            Download PDF
                        </a>
                        <a href="{{ route('invoice-bills.index') }}" class="ml-4 text-sm text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white">
                            {{ __('Back to list') }}
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @push('modals')
        <script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"></script>
        <script>
            document.addEventListener('DOMContentLoaded', function() {
                new QRCode(document.getElementById('qrcode'), {
                    text: "{{ $invoiceBill->payload }}",
                    width: 256,
                    height: 256,
                    colorDark: '#000000',
                    colorLight: '#FFFFFF',
                    correctLevel: QRCode.CorrectLevel.M
                });
            });
        </script>
    @endpush
</x-app-layout>
